# Generated by Django 4.1.1 on 2022-10-29 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('everything', '0020_adminregistration_password_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo_Bill', models.ImageField(upload_to='')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('Client_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='everything.clientregistration')),
                ('Room_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='everything.roomregestration')),
            ],
        ),
    ]
