# Generated by Django 4.1.3 on 2022-11-25 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_paymentsubmission_photo_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestreservations',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='requestreservations',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
