# Generated by Django 4.1.1 on 2022-10-13 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.IntegerField()),
                ('Date_of_Registration', models.DateField()),
                ('Client_Address', models.CharField(max_length=100)),
                ('Tin_Number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RoomRegestration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Name', models.CharField(max_length=50)),
                ('Room_Type', models.CharField(max_length=50)),
                ('Room_Catagory', models.CharField(max_length=50)),
                ('Floor_No', models.CharField(default='', max_length=100)),
                ('Remark', models.TextField(blank=True, null=True)),
                ('Photo_Room', models.ImageField(default='', upload_to='everything/statics/Photos/1/%Y/%m/%d')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Status', models.CharField(choices=[('have been payed', 'have been payed'), ('is not payed', 'is not payed')], default='have been payed', max_length=50)),
                ('Rent_Status', models.CharField(choices=[('is currently rented', 'is currently rented'), ('is not rented yet', 'is not rented yet')], default='is currently rented', max_length=70)),
                ('Photo_Bill', models.ImageField(default='', upload_to='everything/statics/Photos/2/%Y/%m/%d')),
                ('Client_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='everything.clientregistration')),
                ('Room_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='everything.roomregestration')),
            ],
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='Room_Been_Registered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='everything.roomregestration'),
        ),
    ]
