# Generated by Django 4.1.1 on 2022-10-15 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomregestration',
            name='Photo_Room',
            field=models.ImageField(default='', upload_to='statics/Photos/1/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='roomstatus',
            name='Photo_Bill',
            field=models.ImageField(default='', upload_to='statics/Photos/2/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='BookingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.TextField(max_length=50)),
                ('Begining_Day', models.DateField()),
                ('Ending_Day', models.DateField()),
                ('Agrement_Starting_Date', models.DateField()),
                ('Agrement_Ending_Date', models.DateField()),
                ('Monthly_Fee', models.IntegerField()),
                ('Advance_payed', models.IntegerField()),
                ('Payment_Method', models.CharField(choices=[('Every Month', 'Every Month'), ('Every 3 month', 'Every 3 Month'), ('Every 6 Month', 'Every 6 Month'), ('Every Year', 'Every Year')], max_length=200, null=True)),
                ('Phone_Number', models.IntegerField()),
                ('Date_of_Registration', models.DateField()),
                ('Client_Address', models.CharField(max_length=100)),
                ('Tin_Number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Room_Number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='everything.roomregestration')),
            ],
        ),
    ]
