# Generated by Django 4.1.1 on 2022-10-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0003_alter_bookingform_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomregestration',
            name='Photo_Room',
            field=models.ImageField(null=True, upload_to='statics/Photos/1/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='roomstatus',
            name='Photo_Bill',
            field=models.ImageField(null=True, upload_to='statics/Photos/2/%Y/%m/%d'),
        ),
    ]
