# Generated by Django 4.1.1 on 2022-10-18 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('everything', '0006_alter_roomregestration_photo_room'),
    ]

    
