# Generated by Django 4.1.1 on 2022-10-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0007_alter_adminregistration_admin_name'),
    ]

