# Generated by Django 4.1.1 on 2022-10-20 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0008_alter_adminregistration_admin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregistration',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
