# Generated by Django 4.1.1 on 2022-10-22 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0009_clientregistration_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingform',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roomstatus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomstatus',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roomregestration',
            name='Photo_Room',
            field=models.ImageField(blank=True, null=True, upload_to='Photos/1'),
        ),
        migrations.AlterField(
            model_name='roomstatus',
            name='Photo_Bill',
            field=models.ImageField(null=True, upload_to='Photos/2'),
        ),
    ]
