# Generated by Django 4.1.1 on 2022-10-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0010_bookingform_created_bookingform_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingform',
            name='Monthly_Fee',
        ),
        migrations.AddField(
            model_name='roomregestration',
            name='Rent_Price',
            field=models.IntegerField(),
        ),
    ]
