# Generated by Django 4.1.1 on 2022-10-25 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0011_remove_bookingform_monthly_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomregestration',
            name='Rent_Price',
        ),
        migrations.AddField(
            model_name='roomregestration',
            name='Room_cost',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
