# Generated by Django 4.1.1 on 2022-10-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0012_remove_roomregestration_rent_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomregestration',
            name='Room_cost',
        ),
    ]
