# Generated by Django 4.1.1 on 2022-10-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0013_remove_roomregestration_room_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomregestration',
            name='Rent_Price',
            field=models.IntegerField(default=0),
        ),
    ]
