# Generated by Django 4.1.1 on 2022-10-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0014_roomregestration_rent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomregestration',
            name='Rent_Price',
            field=models.IntegerField(),
        ),
    ]
