# Generated by Django 4.1.1 on 2022-10-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0012_remove_roomregestration_rent_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomregestration',
            name='Monthly_fee',
            field=models.IntegerField(),
        ),
    ]
