# Generated by Django 4.1.1 on 2022-10-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0015_alter_roomregestration_rent_price'),
        ('everything', '0016_rename_rent_price_roomregestration_monthly_fee'),
    ]

    operations = [
    ]
