# Generated by Django 4.1.1 on 2022-10-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0017_merge_20221026_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomregestration',
            old_name='Monthly_fee',
            new_name='Room_costes',
        ),
        migrations.RemoveField(
            model_name='roomregestration',
            name='Rent_Price',
        ),
        migrations.AlterField(
            model_name='roomstatus',
            name='Photo_Bill',
            field=models.ImageField(null=True, upload_to='Photos/3'),
        ),
    ]
