# Generated by Django 4.1.1 on 2022-10-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0018_rename_monthly_fee_roomregestration_room_costes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregistration',
            name='Password_assigned',
            field=models.CharField(default='', max_length=10),
        ),
    ]
