# Generated by Django 4.1.1 on 2022-10-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0019_clientregistration_password_assigned'),
    ]

