# Generated by Django 4.1.1 on 2022-10-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0020_adminregistration_password_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomstatus',
            name='Photo_Bill',
        ),
        migrations.RemoveField(
            model_name='roomstatus',
            name='Rent_Status',
        ),
    ]
