# Generated by Django 4.1.3 on 2022-11-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0021_remove_roomstatus_photo_bill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomstatus',
            name='Room_Id',
        ),
    ]
