# Generated by Django 4.1.3 on 2022-11-25 05:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('everything', '0023_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admin1',
        ),
    ]
