# Generated by Django 4.1.3 on 2022-11-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0024_rename_admin_admin1'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregistration',
            name='Payment_Status',
            field=models.CharField(choices=[('have been payed', 'have been payed'), ('is not payed', 'is not payed')], default='have been payed', max_length=50),
        ),
    ]
