# Generated by Django 4.1.3 on 2022-11-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0025_clientregistration_payment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomStatus',
        ),
    ]
