# Generated by Django 5.1.1 on 2024-09-09 14:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_review_reviewer'),
        ('rooms', '0002_roomsobject_created_roomsobject_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelOject',
            new_name='HotelObject',
        ),
    ]
