# Generated by Django 5.1.1 on 2024-09-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_rename_hoteloject_hotelobject'),
        ('rooms', '0002_roomsobject_created_roomsobject_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
